# Generated by Django 3.1.3 on 2021-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_title', models.CharField(max_length=100)),
                ('current_poster', models.FileField(upload_to='')),
            ],
        ),
    ]
